- name: Download Dependencies 
  yum:
    name: "{{ item }}"
    state: latest
    loop: "{{ p }}"
- name: Start Pkg
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
    loop: "{{ p }}"

